---
- name: Create Docker registry docroot.
  file:
    state: directory
    path: "{{ docker_registry_data_directory }}"
    # Ownership necessary for nginx?
    #   owner: www-data
    #   group: www-data
    mode: "0755"

- name: Run docker registry container
  docker_container:
    expose: "{{ docker_registry_expose_port }}"
    image: "registry:2"
    name: registry
    ports: "{{ docker_registry_expose_port }}:{{ docker_registry_expose_port }}"
    volumes:
      - "{{ docker_registry_data_directory }}:{{ docker_registry_data_directory }}"
    pull: true
    restart_policy: unless-stopped
    # "reloaded" does not appear to be idempotent
    state: started
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker_registry_data_directory }}"
